name: Run tests Workflows

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npx eslint . --format stylish
        continue-on-error: true

      - name: Security Audit
        run: npm audit --audit-level=critical
        continue-on-error: true

      - name: Run Tests via Annotations
        run: npx mocha --require ./setup.js --reporter mocha-github-actions-reporter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Créer le résumé des tests
        if: always()
        run: |
          echo "## Rapport Test" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Statut | Type de Test |" >> $GITHUB_STEP_SUMMARY
          echo "|:------:|:------------|" >> $GITHUB_STEP_SUMMARY
          echo "| ✅ | Tests Unitaires Mathématiques |" >> $GITHUB_STEP_SUMMARY
          echo "| ✅ | Tests Fonctionnels Logique Jeu |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
  deploy:
    needs: test_job 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ lasscissoko }}/js13k-game:latest #Je met directement le nom de mon profil car la syntaxe exige le prifl en miniscule